version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    environment:
      - VITE_DD_APPLICATION_ID=${VITE_DD_APPLICATION_ID}
      - VITE_DD_CLIENT_TOKEN=${VITE_DD_CLIENT_TOKEN}
      - VITE_DD_SITE=${VITE_DD_SITE:-datadoghq.com}
      - VITE_DD_ENV=${VITE_DD_ENV:-development}
      - VITE_DD_VERSION=${VITE_DD_VERSION:-1.0.0}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:3000}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - default

networks:
  default:
    driver: bridge 