development:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: app_development

test:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: app_production

production:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: app_production
