default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("DATABASE_USERNAME", 'postgres') %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", '12345') %>
  host: <%= ENV.fetch("DATABASE_HOST", 'db') %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", 'api_development') %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_TEST", 'api_test') %>

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME_PROD", "api_production") %>
  queue:
    <<: *default
    database: <%= ENV.fetch("DATABASE_QUEUE_PROD", "api_queue_production") %>
  cache:
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME_PROD", "api_production") %>

