services:
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./bin/wait-for-it.sh:/usr/local/bin/wait-for-it.sh:ro
    entrypoint: ["/bin/sh", "-c", "wait-for-it.sh frontend:3001 -t 30 && nginx -g 'daemon off;'"]
    networks:
      - app_net

networks:
  app_net:
    external: true

