version: '3'

x-common-env: &common-env
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_USERNAME: ${DATABASE_USERNAME}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  DATABASE_NAME: ${DATABASE_NAME}
  DATABASE_NAME_TEST: ${DATABASE_NAME_TEST}
  DATABASE_NAME_PROD: ${DATABASE_NAME_PROD}
  REDIS_URL: ${REDIS_URL}
  EXCHANGE_API_DATE: ${EXCHANGE_API_DATE}
  EXCHANGE_API_VERSION: ${EXCHANGE_API_VERSION}
  EXCHANGE_CURRENCIES: ${EXCHANGE_CURRENCIES}
  BASE_CURRENCY: ${BASE_CURRENCY}
  CSV_MAX_LINES: ${CSV_MAX_LINES}
  RAILS_MAX_THREADS: ${RAILS_MAX_THREADS}

tasks:

  dev:
    desc: "Set up DB for development and start development environment"
    deps: [db-dev]
    cmds:
      -  cd backend && docker-compose up --build

  db-dev:
    desc: "Create and migrate database for development"
    cmds:
      - cd backend && docker-compose run --rm backend rake db:create db:migrate RAILS_ENV=development

  down:
    desc: "Stop development containers"
    cmds:
      - cd backend && docker-compose down

  frontend-dev:
    desc: "Bring up the development environment:frontend"
    cmds:
      - cd frontend && npm run dev 


  test-backend-rspec:
    desc: "Run backend RSpec tests inside container with test environment"
    cmds:
      - cd backend && docker-compose -f docker-compose.test.yml  run --rm backend rake db:create db:migrate RAILS_ENV=test
      - cd backend && docker-compose -f docker-compose.test.yml run --rm backend bundle exec rspec

  test-backend-cucumber:
    desc: "Run backend Cucumber tests inside container with test environment"
    cmds:
      - cd backend && docker-compose -f docker-compose.test.yml run --rm backend rake db:create db:migrate RAILS_ENV=test
      - cd backend && docker-compose -f docker-compose.test.yml run --rm backend bundle exec cucumber

  test-frontend:
    desc: "Run frontend tests inside container using the default docker-compose"
    cmds:
      - cd frontend && docker-compose -f docker-compose.test.yml run --rm frontend_test npm install && npm  run test

  test-all:
    desc: "Run all tests: backend (RSpec & Cucumber) and frontend"
    deps: [test-backend-rspec, test-backend-cucumber, test-frontend]

