x-common-env: &common-env
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_USERNAME: ${DATABASE_USERNAME}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  DATABASE_NAME: ${DATABASE_NAME_TEST}
  REDIS_URL: ${REDIS_URL}
  EXCHANGE_API_DATE: ${EXCHANGE_API_DATE}
  EXCHANGE_API_VERSION: ${EXCHANGE_API_VERSION}
  EXCHANGE_CURRENCIES: ${EXCHANGE_CURRENCIES}
  BASE_CURRENCY: ${BASE_CURRENCY}
  CSV_MAX_LINES: ${CSV_MAX_LINES}
  RAILS_MAX_THREADS: ${RAILS_MAX_THREADS}

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT:-5432}:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment: *common-env

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment: *common-env

volumes:
  db-data:

