x-common-env: &common-env
  RAILS_ENV: production
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_USERNAME: ${DATABASE_USERNAME}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  DATABASE_NAME: ${DATABASE_NAME_PROD}
  DATABASE_QUEUE_PROD: ${DATABASE_QUEUE_PROD}
  REDIS_URL: ${REDIS_URL}
  EXCHANGE_API_DATE: ${EXCHANGE_API_DATE}
  EXCHANGE_API_VERSION: ${EXCHANGE_API_VERSION}
  EXCHANGE_CURRENCIES: ${EXCHANGE_CURRENCIES}
  BASE_CURRENCY: ${BASE_CURRENCY}
  CSV_MAX_LINES: ${CSV_MAX_LINES}
  RAILS_MAX_THREADS: ${RAILS_MAX_THREADS}

services:
  backend:
    build: .
    command: sh -c "bundle exec rake db:create && bundle exec rake db:migrate && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment: *common-env
    networks:
      - app_net

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment: *common-env
    networks:
      - app_net

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME_PROD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    networks:
      - app_net

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - app_net

networks:
  app_net:
    external: true

volumes:
  db-data:

