name: Backend CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myapp_test
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker containers
        run: |
          cd backend
          docker-compose -f docker-compose.test.yml build

      - name: Setup Database
        run: |
          cd backend
          docker-compose -f docker-compose.test.yml run --rm backend rake db:create db:migrate RAILS_ENV=test

      - name: Run RSpec Tests
        run: |
          cd backend
          docker-compose -f docker-compose.test.yml run --rm backend bundle exec rspec

      - name: Run Cucumber Tests
        run: |
          cd backend
          docker-compose -f docker-compose.test.yml run --rm backend bundle exec cucumber

      - name: Shutdown Docker Compose
        run: |
          cd backend
          docker-compose -f docker-compose.test.yml down